builds:
  - binary: ipr
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd
    env:
      - CGO_ENABLED=0

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: ipr
    homepage: "https://github.com/qba73/ipr"
    tap:
      owner: qba73
      name: homebrew-qba73
    commit_author:
      name: qba73
      email: info@jarosz.dev

checksum:
  name_template: "checksums.txt"
